openapi: "3.0.2"
info:
  version: "1.0.0"
  title: API for courses
  description: Work with courses.Allows to display list of courses, create, edit and delete courses.
  contact:
    name: "Ilikbaeva Valeriia"
    url: "https://github.com/Valeeerie"
    email: "valeria180501@mail.ru"
  license: 
    name: "Apache 2.0"
    url: "https://www.apache.org/licenses/LICENSE-2.0"

servers:
  - url: "https://virtserver.swaggerhub.com/Tensor-School/TSLessons/1.0.0"
    description: Swagger-сервер для тестовых запросов
  - url: "https://beta.mycoolsite.com/api/"
    description: Тестовый сервер нашего сайта
  - url: "https://{dev}mycoolsite.com/api/{version}"
    description: Боевой сервер нашего сайта
    
    variables:
      dev:
        enum:
          - dev
          - test
          - fix
        default: dev
        description: Версия тестового стенда
      version:
        default: v2
        description: Версия API
        
tags:
  - name: Teachers
    description: Преподаватели, доступен расширенный функционал управления курсами
  - name: Students
    description: Студенты, доступен функционал записи на курсы и их прохождение

paths:
  "/lessons":
    get:
      tags:
      - Students
      summary: Просмотр и поиск курсов
      description: Получает список доступных курсов для записи, поддерживает поиск
      operationId: searchLessons
      parameters:
      - name: searchString
        in: query
        description: Опицональный параметр для поиска курсов
        required: false
        schema:
            type: "string"
            
      - name: offset
        in: query
        description: Количество записей которые нужно пропустить, навигация
        required: false
        schema:
          type: integer
          format: int32
          minimum: 0
          
      - name: limit
        in: query
        description: Макс кол-во записей в ответе
        schema:
          type: integer
          format: int32
          minimum: 0
          maximum: 50
          
      responses:
        200:
          description: Выдает список курсов по запросу
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/tut_poka_nothing"
        400:
          description: Некорректные вводные параметры
          content:
            text/plain:
              schema:
                title: not found
                type: string
                example: Not found
              
  "/applyform":
    post:
      tags:
      - Students
      summary: Запись на курс
      description: Записывает на курс
      operationId: applyToLesson
      responses:
        200:
          description: successful operation
        400:
          description: Invalid status value 
  "/addСourse":
    post:
      tags:
      - Teachers
      summary: Добавление курса
      description: Добавляет курс
      operationId: applyNewCourse
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Pet not found
        405:
          description: Validation exception
          
  "/deleteCourse":
    delete:
      tags:
      - Teachers
      summary: Удаление курса
      description: Удаляет курс
      operationId: deleteCourse
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Not found
        405:
          description: Validation exception
  
  "/getStudentsList":
    get:
      tags:
      - Teachers
      summary: Получение списка учеников
      description: Получает список учеников на курсе
      operationId: getStudentsList
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Not found
        405:
          description: Validation exception